fl="colony2.dat"

cat(paste("\'",colony.base,"\'  !Dataset name\n",sep=""), file=fl)
cat(paste("\'",colony.base,"\'  !Output file name\n",sep=""), file=fl, append=T)
cat(paste(nrow(vdf), "          ! Number of offspring in the sample\n", sep=""), file=fl, append=T)
cat(paste(ncol(vdf)/2, "           ! Number of loci\n", sep=""), file=fl, append=T)
#cat(paste(round(runif(1)*1000),"        ! Seed for random number generator\n",sep=""), file=fl, append=T)
cat(paste(1234,"        ! Seed for random number generator\n",sep=""), file=fl, append=T)
cat("0           ! 0/1=Not updating/updating allele frequency\n", file=fl, append=T)
cat("2           ! 2/1=Dioecious/Monoecious species\n", file=fl, append=T)
cat("1           ! 0/1=No inbreeding/inbreeding\n", file=fl, append=T)
cat("0           ! 0/1=Diploid species/HaploDiploid species\n", file=fl, append=T)
cat("0  0        ! 0/1=Polygamy/Monogamy for males & females\n", file=fl, append=T)
cat("1           ! 0/1=Clone inference =No/Yes\n", file=fl, append=T)
cat("1           ! 0/1=Full sibship size scaling =No/Yes\n", file=fl, append=T)
cat("1 1.0 1.0   ! 0,1,2,3=No,weak,medium,strong sibship size prior; mean paternal & meteral sibship size\n", file=fl, append=T)
cat("0           ! 0/1=Unknown/Known population allele frequency\n", file=fl, append=T)
cat("1         ! Number of runs\n", file=fl, append=T)
cat("2         ! Length of run\n", file=fl, append=T)
cat("0         ! 0/1=Monitor method by Iterate\n", file=fl, append=T)
cat("100000    ! Monitor interval in Iterate\n", file=fl, append=T)
cat("0         ! non-Windows version\n", file=fl, append=T)
cat("1         ! Fulllikelihood\n", file=fl, append=T)
cat("2         ! 1/2/3=low/medium/high Precision for Fulllikelihood\n", file=fl, append=T)
cat("mk@\n", file=fl, append=T)
cat("0@\n", file=fl, append=T)
cat(paste(er1, "@\n", sep=""), file=fl, append=T)
cat(paste(er2, "@\n", sep=""), file=fl, append=T)

write.table(vdf, append=T, file=fl, quote=F, sep="\t", col.names=F, row.names=T, na="0")

cat("0.5 0.5 \n", file=fl, append=T)
cat("0 0 \n", file=fl, append=T)
cat("0 0 \n", file=fl, append=T)
cat("0 0 \n", file=fl, append=T)
cat("0 \n", file=fl, append=T)
cat("0 \n", file=fl, append=T)
cat("0 \n", file=fl, append=T)
cat("0 \n", file=fl, append=T)
cat("0 \n", file=fl, append=T)
cat("0 \n", file=fl, append=T)
